### ISSUE TITLE
[rush] Error running "rush link"

### ISSUE THREAD

**Issue by Wisedemic** [microsoft/web-build-tools#1313]
Hello!

This is my rush.json file:
```
{
	"$schema": "https://developer.microsoft.com/json-schemas/rush/v5/rush.schema.json",
	"rushVersion": "5.7.3",

	"pnpmVersion": "3.4.1",

	// "npmVersion": "4.5.0",
	// "yarnVersion": "1.9.4",

	"pnpmOptions": {},

	"nodeSupportedVersionRange": ">=10.13.0 <11.0.0",

	// "projectFolderMinDepth": 2,
	"projectFolderMaxDepth": 3,
	"gitPolicy": {},

	"repository": {},

	"eventHooks": {
		"preRushInstall": [],

		"postRushInstall": [],

		"preRushBuild": [],

		"postRushBuild": []
	},

	"variants": [],

	"projects": [
		{
			"packageName": "web",
			"projectFolder": "packages/web",
			"reviewCategory": "production",
			"cyclicDependencyProjects": ["shared-ui"]
		},
		{
			"packageName": "shared-ui",
			"projectFolder": "packages/shared-ui",
			"reviewCategory": "production"
		}
	]
}

```

I ran this command: ``` PS C:\Users\Tristan\Documents\CODE\NODE> rush link ```

And then received this error:

```

Rush Multi-Project Build Tool 5.7.3 - https://rushjs.io

Starting "rush link"

Linking projects together...

LINKING: shared-ui

ERROR: Internal Error: Cannot find installed dependency "@babel/core" in
"C:\Users\Tristan\Documents\CODE\NODE\common\temp\node_modules\.local\C%3A%2FUsers%2FTristan%2FDocuments%2FCODE%2FNODE%2Fcommon%2Ftemp%2Fprojects%2Fshared-ui.tgz\node_modules"

You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.
```

Perhaps I have misconfigured my rush.json file haha. Please let me know :)

**Comment by octogonz** [comment]
What happens if you run `rush install` instead of `rush link`?  (`rush link` is a rarely used command, and it's expected to fail if the `rush install` state is invalid.)

**Comment by Wisedemic** [comment]
After running rush install 

```
PS C:\Users\Tristan\Documents\CODE\NODE> rush install

Rush Multi-Project Build Tool 5.7.3 - https://rushjs.io

Starting "rush install"

Ignoring Git validation because this is not a Git working folder.

Trying to acquire lock for pnpm-3.4.1
Acquired lock for pnpm-3.4.1
Found pnpm version 3.4.1 in C:\Users\Tristan\.rush\node-v10.15.3\pnpm-3.4.1

Symlinking "C:\Users\Tristan\Documents\CODE\NODE\common\temp\pnpm-local"
  --> "C:\Users\Tristan\.rush\node-v10.15.3\pnpm-3.4.1"

Updating temp projects in C:\Users\Tristan\Documents\CODE\NODE\common\temp\projects
Copying C:\Users\Tristan\Documents\CODE\NODE\common\config\rush\.npmrc --> C:\Users\Tristan\Documents\CODE\NODE\common\temp\.npmrc
Updating C:\Users\Tristan\Documents\CODE\NODE\common\temp\pnpmfile.js
Updating C:\Users\Tristan\Documents\CODE\NODE\common\temp\projects\web.tgz
Finished creating temporary modules (0.26 seconds)

Checking node_modules in C:\Users\Tristan\Documents\CODE\NODE\common\temp

Deleting files from C:\Users\Tristan\Documents\CODE\NODE\common\temp\node_modules

Running "pnpm install" in C:\Users\Tristan\Documents\CODE\NODE\common\temp

Using hooks from: C:\Users\Tristan\Documents\CODE\NODE\common\temp\pnpmfile.js
readPackage hook is declared. Manifests of dependencies might get overridden
Packages: +824
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Resolving: total 730, reused 0, downloaded 730, done
node_modules/.registry.npmjs.org/core-js-pure/3.1.3/node_modules/core-js-pure: Running postinstall script, done in 890ms
node_modules/.registry.npmjs.org/core-js/2.6.9/node_modules/core-js: Running postinstall script, done in 698ms
node_modules/.registry.npmjs.org/fsevents/1.2.9/node_modules/fsevents: Running install script, done in 405ms

dependencies:
+ @babel/core 7.4.5
+ @babel/preset-env 7.4.5
+ @babel/preset-react 7.0.0
+ @rush-temp/shared-ui 0.0.0
+ @rush-temp/web 0.0.0
+ next 8.1.0
+ postcss-modules 1.4.1
+ react 16.8.6
+ react-dom 16.8.6
+ rollup 1.13.1
+ rollup-plugin-babel 4.3.2
+ rollup-plugin-commonjs 10.0.0
+ rollup-plugin-node-resolve 5.0.1
+ rollup-plugin-postcss 2.0.3


Linking projects together...

LINKING: shared-ui
Purging C:\Users\Tristan\Documents\CODE\NODE\packages\shared-ui\node_modules

LINKING: web
Purging C:\Users\Tristan\Documents\CODE\NODE\packages\web\node_modules
Writing "C:\Users\Tristan\Documents\CODE\NODE\common\temp\rush-link.json"

Linking finished successfully. (0.36 seconds)

Next you should probably run "rush build" or "rush rebuild"

Rush install finished successfully. (1 minute 5.0 seconds)
```

and rush build
```
PS C:\Users\Tristan\Documents\CODE\NODE> rush build

Rush Multi-Project Build Tool 5.7.3 - https://rushjs.io

Starting "rush build"

Executing a maximum of 3 simultaneous processes...

[shared-ui] started
[web] started

src/index.js → dist/index.js...
created dist/index.js in 2.4s
1 of 2: [shared-ui] completed with warnings in 4.92 seconds


Failed to compile.
./pages/index.js
Module not found: Can't resolve 'shared-ui' in 'C:\Users\Tristan\Documents\CODE\NODE\packages\web\pages'

> Build error occurred
Error: > Build failed because of webpack errors
    at Object.build [as default] (C:\Users\Tristan\Documents\CODE\NODE\common\temp\node_modules\.registry.npmjs.org\next\8.1.0_react-dom@16.8.6+react@16.8.6\node_modules\next\dist\build\index.js:192:15)

1 of 2: [web] failed to build!

SUCCESS WITH WARNINGS (1)
================================
shared-ui (4.92 seconds)

src/index.js → dist/index.js...
created dist/index.js in 2.4s
================================

FAILURE (1)
================================
web (10.71 seconds)
Failed to compile.
./pages/index.js
Module not found: Can't resolve 'shared-ui' in 'C:\Users\Tristan\Documents\CODE\NODE\packages\web\pages'
> Build error occurred
Error: > Build failed because of webpack errors
    at Object.build [as default] (C:\Users\Tristan\Documents\CODE\NODE\common\temp\node_modules\.registry.npmjs.org\next\8.1.0_react-dom@16.8.6+react@16.8.6\node_modules\next\dist\build\index.js:192:15)
================================

[web] Returned error code: 1

Error: Project(s) failed to build
rush build - Errors! (10.81 seconds)

```

**Comment by Wisedemic** [comment]
> After running rush install
> 
> ```
> PS C:\Users\Tristan\Documents\CODE\NODE> rush install
> 
> Rush Multi-Project Build Tool 5.7.3 - https://rushjs.io
> 
> Starting "rush install"
> 
> Ignoring Git validation because this is not a Git working folder.
> 
> Trying to acquire lock for pnpm-3.4.1
> Acquired lock for pnpm-3.4.1
> Found pnpm version 3.4.1 in C:\Users\Tristan\.rush\node-v10.15.3\pnpm-3.4.1
> 
> Symlinking "C:\Users\Tristan\Documents\CODE\NODE\common\temp\pnpm-local"
>   --> "C:\Users\Tristan\.rush\node-v10.15.3\pnpm-3.4.1"
> 
> Updating temp projects in C:\Users\Tristan\Documents\CODE\NODE\common\temp\projects
> Copying C:\Users\Tristan\Documents\CODE\NODE\common\config\rush\.npmrc --> C:\Users\Tristan\Documents\CODE\NODE\common\temp\.npmrc
> Updating C:\Users\Tristan\Documents\CODE\NODE\common\temp\pnpmfile.js
> Updating C:\Users\Tristan\Documents\CODE\NODE\common\temp\projects\web.tgz
> Finished creating temporary modules (0.26 seconds)
> 
> Checking node_modules in C:\Users\Tristan\Documents\CODE\NODE\common\temp
> 
> Deleting files from C:\Users\Tristan\Documents\CODE\NODE\common\temp\node_modules
> 
> Running "pnpm install" in C:\Users\Tristan\Documents\CODE\NODE\common\temp
> 
> Using hooks from: C:\Users\Tristan\Documents\CODE\NODE\common\temp\pnpmfile.js
> readPackage hook is declared. Manifests of dependencies might get overridden
> Packages: +824
> +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
> Resolving: total 730, reused 0, downloaded 730, done
> node_modules/.registry.npmjs.org/core-js-pure/3.1.3/node_modules/core-js-pure: Running postinstall script, done in 890ms
> node_modules/.registry.npmjs.org/core-js/2.6.9/node_modules/core-js: Running postinstall script, done in 698ms
> node_modules/.registry.npmjs.org/fsevents/1.2.9/node_modules/fsevents: Running install script, done in 405ms
> 
> dependencies:
> + @babel/core 7.4.5
> + @babel/preset-env 7.4.5
> + @babel/preset-react 7.0.0
> + @rush-temp/shared-ui 0.0.0
> + @rush-temp/web 0.0.0
> + next 8.1.0
> + postcss-modules 1.4.1
> + react 16.8.6
> + react-dom 16.8.6
> + rollup 1.13.1
> + rollup-plugin-babel 4.3.2
> + rollup-plugin-commonjs 10.0.0
> + rollup-plugin-node-resolve 5.0.1
> + rollup-plugin-postcss 2.0.3
> 
> 
> Linking projects together...
> 
> LINKING: shared-ui
> Purging C:\Users\Tristan\Documents\CODE\NODE\packages\shared-ui\node_modules
> 
> LINKING: web
> Purging C:\Users\Tristan\Documents\CODE\NODE\packages\web\node_modules
> Writing "C:\Users\Tristan\Documents\CODE\NODE\common\temp\rush-link.json"
> 
> Linking finished successfully. (0.36 seconds)
> 
> Next you should probably run "rush build" or "rush rebuild"
> 
> Rush install finished successfully. (1 minute 5.0 seconds)
> ```
> 
> and rush build
> 
> ```
> PS C:\Users\Tristan\Documents\CODE\NODE> rush build
> 
> Rush Multi-Project Build Tool 5.7.3 - https://rushjs.io
> 
> Starting "rush build"
> 
> Executing a maximum of 3 simultaneous processes...
> 
> [shared-ui] started
> [web] started
> 
> src/index.js → dist/index.js...
> created dist/index.js in 2.4s
> 1 of 2: [shared-ui] completed with warnings in 4.92 seconds
> 
> 
> Failed to compile.
> ./pages/index.js
> Module not found: Can't resolve 'shared-ui' in 'C:\Users\Tristan\Documents\CODE\NODE\packages\web\pages'
> 
> > Build error occurred
> Error: > Build failed because of webpack errors
>     at Object.build [as default] (C:\Users\Tristan\Documents\CODE\NODE\common\temp\node_modules\.registry.npmjs.org\next\8.1.0_react-dom@16.8.6+react@16.8.6\node_modules\next\dist\build\index.js:192:15)
> 
> 1 of 2: [web] failed to build!
> 
> SUCCESS WITH WARNINGS (1)
> ================================
> shared-ui (4.92 seconds)
> 
> src/index.js → dist/index.js...
> created dist/index.js in 2.4s
> ================================
> 
> FAILURE (1)
> ================================
> web (10.71 seconds)
> Failed to compile.
> ./pages/index.js
> Module not found: Can't resolve 'shared-ui' in 'C:\Users\Tristan\Documents\CODE\NODE\packages\web\pages'
> > Build error occurred
> Error: > Build failed because of webpack errors
>     at Object.build [as default] (C:\Users\Tristan\Documents\CODE\NODE\common\temp\node_modules\.registry.npmjs.org\next\8.1.0_react-dom@16.8.6+react@16.8.6\node_modules\next\dist\build\index.js:192:15)
> ================================
> 
> [web] Returned error code: 1
> 
> Error: Project(s) failed to build
> rush build - Errors! (10.81 seconds)
> ```

**Comment by Wisedemic** [comment]
```
PS C:\Users\Tristan\Documents\CODE\NODE> rush install

Rush Multi-Project Build Tool 5.7.3 - https://rushjs.io

Starting "rush install"

Ignoring Git validation because this is not a Git working folder.

Trying to acquire lock for pnpm-3.4.1
Acquired lock for pnpm-3.4.1
Found pnpm version 3.4.1 in C:\Users\Tristan\.rush\node-v10.15.3\pnpm-3.4.1

Symlinking "C:\Users\Tristan\Documents\CODE\NODE\common\temp\pnpm-local"
  --> "C:\Users\Tristan\.rush\node-v10.15.3\pnpm-3.4.1"

Updating temp projects in C:\Users\Tristan\Documents\CODE\NODE\common\temp\projects
Copying C:\Users\Tristan\Documents\CODE\NODE\common\config\rush\.npmrc --> C:\Users\Tristan\Documents\CODE\NODE\common\temp\.npmrc
Updating C:\Users\Tristan\Documents\CODE\NODE\common\temp\pnpmfile.js
Updating C:\Users\Tristan\Documents\CODE\NODE\common\temp\projects\web.tgz
Finished creating temporary modules (0.26 seconds)

Checking node_modules in C:\Users\Tristan\Documents\CODE\NODE\common\temp

Deleting files from C:\Users\Tristan\Documents\CODE\NODE\common\temp\node_modules

Running "pnpm install" in C:\Users\Tristan\Documents\CODE\NODE\common\temp

Using hooks from: C:\Users\Tristan\Documents\CODE\NODE\common\temp\pnpmfile.js
readPackage hook is declared. Manifests of dependencies might get overridden
Packages: +824
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Resolving: total 730, reused 0, downloaded 730, done
node_modules/.registry.npmjs.org/core-js-pure/3.1.3/node_modules/core-js-pure: Running postinstall script, done in 890ms
node_modules/.registry.npmjs.org/core-js/2.6.9/node_modules/core-js: Running postinstall script, done in 698ms
node_modules/.registry.npmjs.org/fsevents/1.2.9/node_modules/fsevents: Running install script, done in 405ms

dependencies:
+ @babel/core 7.4.5
+ @babel/preset-env 7.4.5
+ @babel/preset-react 7.0.0
+ @rush-temp/shared-ui 0.0.0
+ @rush-temp/web 0.0.0
+ next 8.1.0
+ postcss-modules 1.4.1
+ react 16.8.6
+ react-dom 16.8.6
+ rollup 1.13.1
+ rollup-plugin-babel 4.3.2
+ rollup-plugin-commonjs 10.0.0
+ rollup-plugin-node-resolve 5.0.1
+ rollup-plugin-postcss 2.0.3

Linking projects together...

LINKING: shared-ui
Purging C:\Users\Tristan\Documents\CODE\NODE\packages\shared-ui\node_modules

LINKING: web
Purging C:\Users\Tristan\Documents\CODE\NODE\packages\web\node_modules
Writing "C:\Users\Tristan\Documents\CODE\NODE\common\temp\rush-link.json"

Linking finished successfully. (0.36 seconds)

Next you should probably run "rush build" or "rush rebuild"

Rush install finished successfully. (1 minute 5.0 seconds)

```


```
PS C:\Users\Tristan\Documents\CODE\NODE> rush build

Rush Multi-Project Build Tool 5.7.3 - https://rushjs.io

Starting "rush build"

Executing a maximum of 3 simultaneous processes...

[shared-ui] started
[web] started

src/index.js → dist/index.js...
created dist/index.js in 2.4s
1 of 2: [shared-ui] completed with warnings in 4.92 seconds
Failed to compile.

./pages/index.js
Module not found: Can't resolve 'shared-ui' in 'C:\Users\Tristan\Documents\CODE\NODE\packages\web\pages'

> Build error occurred
Error: > Build failed because of webpack errors
    at Object.build [as default] (C:\Users\Tristan\Documents\CODE\NODE\common\temp\node_modules\.registry.npmjs.org\next\8.1.0_react-dom@16.8.6+react@16.8.6\node_modules\next\dist\build\index.js:192:15)

1 of 2: [web] failed to build!

SUCCESS WITH WARNINGS (1)
================================
shared-ui (4.92 seconds)

src/index.js → dist/index.js...
created dist/index.js in 2.4s
================================

FAILURE (1)
================================
web (10.71 seconds)
Failed to compile.
./pages/index.js
Module not found: Can't resolve 'shared-ui' in 'C:\Users\Tristan\Documents\CODE\NODE\packages\web\pages'
> Build error occurred
Error: > Build failed because of webpack errors
    at Object.build [as default] (C:\Users\Tristan\Documents\CODE\NODE\common\temp\node_modules\.registry.npmjs.org\next\8.1.0_react-dom@16.8.6+react@16.8.6\node_modules\next\dist\build\index.js:192:15)
================================

[web] Returned error code: 1

Error: Project(s) failed to build
rush build - Errors! (10.81 seconds)
```

**Comment by Wisedemic** [comment]
I did not intend on closing the issue! Sorry!

**Comment by Wisedemic** [comment]
This is the `CODE/NODE/packages/web/pages/index.js` file that is being run

```
import React, { Fragment } from 'react'
import Link from 'next/link'
import { Header } from 'shared-ui'

const Home = () => (
	<Fragment>
		<Header />
	</Fragment>
)
export default Home

```

**Comment by octogonz** [comment]
Sounds like something is wrong with the package.json for shared-ui, or else the other package.json is simply forgetting to list it as a dependency. Are you able to share a branch with this code? It's hard to diagnose without seeing your projects.

**Comment by Wisedemic** [comment]
package.json for the 'web'
```
{
	"name": "web",
	"version": "0.0.1-beta",
	"scripts": {
		"dev": "next",
		"build": "next build",
		"start": "next start",
		"now-build": "next build"
	},
	"dependencies": {
		"next": "~8.1.0",
		"react": "~16.8.6",
		"react-dom": "~16.8.6"
	}
}
```

package.json for the 'shared-ui'
```
{
	"name": "shared-ui",
	"version": "0.0.1-beta",
	"main": "dist/index.js",
	"scripts": {
		"now-build": "rollup -c",
		"build": "rollup -c"
	},
	"dependencies": {
		"react": "~16.8.6",
		"react-dom": "~16.8.6"
	},
	"devDependencies": {
		"@babel/core": "~7.4.5",
		"@babel/preset-env": "~7.4.5",
		"@babel/preset-react": "~7.0.0",
		"postcss-modules": "^1.4.1",
		"rollup": "~1.13.1",
		"rollup-plugin-babel": "~4.3.2",
		"rollup-plugin-commonjs": "~10.0.0",
		"rollup-plugin-node-resolve": "~5.0.1",
		"rollup-plugin-postcss": "~2.0.3"
	}
}
```

I'll shared the repo if that still isn't enough info! ^^

**Comment by octogonz** [comment]
@Wisedemic sorry it took a while to respond.  The problem is that `shared-ui` is not listed in your `dependencies` for the `web` project:
```json
	"dependencies": {
		"next": "~8.1.0",
		"react": "~16.8.6",
		"react-dom": "~16.8.6"
	}
```

Thus, when you try to import it, it is not found.  You can add it like this:

```json
{
	"name": "web",
	"version": "0.0.1-beta",
	"scripts": {
		"dev": "next",
		"build": "next build",
		"start": "next start",
		"now-build": "next build"
	},
	"dependencies": {
		"next": "~8.1.0",
		"react": "~16.8.6",
		"react-dom": "~16.8.6",
                "shared-ui": "~0.0.1-beta"
	}
}
```

You may also be interested to read about [phantom dependencies](https://rushjs.io/pages/advanced/phantom_deps/), but in this case it was really just a *missing* dependency.  (I can't see how it could possibly have worked, unless somehow `next` had a dependency on `shared-ui`.)

BTW the `rush scan` command can be useful for finding dependencies that you forgot to declare.
