### ISSUE TITLE
RushCommandLineParser Error

### ISSUE THREAD

**Issue by smoustaj** [Microsoft/web-build-tools#224]
Since Version 3.0.8 (also 3.0.9)

When launching `rush generate`, it returns the following error

    Error: The command failed with exit code 1

    at ProjectBuildTask._executeTask (/usr/local/lib/node_modules/@microsoft/rush/lib/taskRunner/ProjectBuildTask.js:88:31)
    at /usr/local/lib/node_modules/@microsoft/rush/lib/taskRunner/ProjectBuildTask.js:31:19
    at ProjectBuildTask.execute (/usr/local/lib/node_modules/@microsoft/rush/lib/taskRunner/ProjectBuildTask.js:28:16)
    at _loop_1 (/usr/local/lib/node_modules/@microsoft/rush/lib/taskRunner/TaskRunner.js:144:18)
    at TaskRunner._startAvailableTasks (/usr/local/lib/node_modules/@microsoft/rush/lib/taskRunner/TaskRunner.js:176:13)
    at /usr/local/lib/node_modules/@microsoft/rush/lib/taskRunner/TaskRunner.js:97:19
    at TaskRunner.execute (/usr/local/lib/node_modules/@microsoft/rush/lib/taskRunner/TaskRunner.js:96:16)
    at RebuildAction.onExecute (/usr/local/lib/node_modules/@microsoft/rush/lib/actions/RebuildAction.js:108:20)
    at RebuildAction.CommandLineAction.execute (/usr/local/lib/node_modules/@microsoft/rush/node_modules/@microsoft/ts-command-line/lib/CommandLineAction.js:40:14)
    at RushCommandLineParser.CommandLineParser.onExecute (/usr/local/lib/node_modules/@microsoft/rush/node_modules/@microsoft/ts-command-line/lib/CommandLineParser.js:90:27)

Instead this error is not reproducible with 3.0.7

**Comment by nickpape-msft** [comment]
Hi @smoustaj - are you still seeing this issue? `rush generate` should not be invoking the TaskRunner/ProjectBuildTask at all (only `rush rebuild` should do that)

**Comment by smoustaj** [comment]
Yes sorry I meant ```rush rebuild```.
Anyway with version 3.11 the problem is resolved.

Thanks
