### ISSUE TITLE
With gulp-core-build@3.1.0, task construction fails

### ISSUE THREAD

**Issue by abettadapur** [Microsoft/web-build-tools#379]
Calling new on a custom task that extends GulpTask<Config> fails with this error

```
TypeError: Class constructor GulpTask cannot be invoked without 'new'
    at new ResxToTsTask (C:\Users\alebet\git\pexweb6\packages\pextasks\lib\gulpTasks\ResxToTsTask.js:23:23)
    at Object.<anonymous> (C:\Users\alebet\git\pexweb6\packages\pexui\gulpfile.js:50:15)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Liftoff.handleArguments (C:\Users\alebet\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (C:\Users\alebet\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:198:16)
    at module.exports (C:\Users\alebet\AppData\Roaming\npm\node_modules\gulp\node_modules\flagged-respawn\index.js:17:3)
    at Liftoff.<anonymous> (C:\Users\alebet\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:190:9)
    at C:\Users\alebet\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:164:9
    at C:\Users\alebet\AppData\Roaming\npm\node_modules\gulp\node_modules\v8flags\index.js:110:14
    at C:\Users\alebet\AppData\Roaming\npm\node_modules\gulp\node_modules\v8flags\index.js:38:12
```

This was succeeding in earlier versions, only to fail in 3.1.0

**Comment by nickpape-msft** [comment]
We updated the build target for our tooling to es6, which means we are now outputting es6 compliant-classes. For the project containing your gulp tasks, (`pextasks`), could you try updating the `tsconfig.json` `target` to `es6`? Note that es6 is compatible with NodeJS runtimes 6.5.11 and up.

**Comment by abettadapur** [comment]
Sure, I can try that.
This should have been a v4 change though, no?

**Comment by nickpape-msft** [comment]
Yes, it should have been. I'm going to close this issue for now, however.
