### ISSUE TITLE
[rush] rush should also link user's modules in common/temp/node_modules

### ISSUE THREAD

**Issue by cancerberoSgx** [microsoft/web-build-tools#645]
Some modules, like typescript, expect that other "plugin" modules to be in its same "node_modules" location in the file system. If one of these "plugin modules" are user's modules managed by rush that will fail because rush doesn't create links for them in  `common/temp/node_modules/`

In my case I have two projects in the rush monorepo: typescript-plugin-1 and example-project . The later depends on the plugin and on  typescript fail to load it from `common/temp/node_modules/` (because it doesn't exists there). My suggestion is that rush link or other command create also links to user's modules (all of them or those that are dependencies)

I have to do that manually using something like https://github.com/iguntur/ln-cli in the postinstall script. 

Note: in production everything is OK, but in development fails. 

typescript language server start  fails like this: 

 ```sh   at Pipe.onread (net.js:560:20)
Info 33   [2:16:49.850] Couldn't find typescript-plugin-ast-inspector
Info 34   [2:16:49.854] Enabling plugin typescript-plugin-add-type from candidate paths: /home/sg/git/typescript-plugins-of-mine/common/temp/node_modules/typescript/lib/tsserver.js/../../..
Info 35   [2:16:49.855] Loading typescript-plugin-add-type from /home/sg/git/typescript-plugins-of-mine/common/temp/node_modules/typescript/lib/tsserver.js/../../.. (resolved to /home/sg/git/typescript-plugins-of-mine/common/temp/node_modules/node_modules)
Info 36   [2:16:49.868] Failed to load module 'typescript-plugin-add-type': Error: Could not resolve JS module 'typescript-plugin-add-type' starting at '/home/sg/git/typescript-plugins-of-mine/common/temp/node_modules/node_modules'. Looked in: /home/sg/git/typescript-plugins-of-mine/common/temp/node_modules/typescript-plugin-add-type/package.json, /home/sg/git/typescript-plugins-of-mine/common/temp/node_modules/typescript-plugin-add-type.js, /home/sg/git/typescript-plugins-of-mine/common/temp/node_modules/typescript-plugin-add-type.jsx, /home/sg/git/typescript-plugins-of-mine/common/temp/node_modules/typescript-plugin-add-type/index.js, /home/sg/git/typescript-plugins-of-mine/common/temp/node_modules/typescript-plugin-add-type/index.jsx, /home/sg/git/typescript-plugins-of-mine/common/node_modules/typescript-plugin-add-type/package.json, /home/sg/git/typescript-plugins-of-mine/common/node_modules/typescript-plugin-add-type.js, /home/sg/git/typescript-plugins-of-mine/common/node_modules/typescript-plugin-add-type.jsx, /home/sg/git/typescript-plugins-of-mine/common/node_modules/typescript-plugin-add-type/index.js, /home/sg/git/typescript-plugins-of-mine/common/node_modules/typescript-plugin-add-type/index.jsx, /home/sg/git/typescript-plugins-of-mine/node_modules/typescript-plugin-add-type/package.json, /home/sg/git/typescript-plugins-of-mine/node_modules/typescript-plugin-add-type.js, /home/sg/git/typescript-plugins-of-mine/node_modules/typescript-plugin-add-type.jsx, /home/sg/git/typescript-plugins-of-mine/node_modules/typescript-plugin-add-type/index.js, /home/sg/git/typescript-plugins-of-mine/node_modules/typescript-plugin-add-type/index.jsx, /home/sg/git/node_modules/typescript-plugin-add-type/package.json, /home/sg/git/node_modules/typescript-plugin-add-type.js, /home/sg/git/node_modules/typescript-plugin-add-type.jsx, /home/sg/git/node_modules/typescript-plugin-add-type/index.js, /home/sg/git/node_modules/typescript-plugin-add-type/index.jsx, /home/sg/node_modules/typescript-plugin-add-type/package.json, /home/sg/node_modules/typescript-plugin-add-type.js, /home/sg/node_modules/typescript-plugin-add-type.jsx, /home/sg/node_modules/typescript-plugin-add-type/index.js, /home/sg/node_modules/typescript-plugin-add-type/index.jsx, /home/node_modules/typescript-plugin-add-type/package.json, /home/node_modules/typescript-plugin-add-type.js, /home/node_modules/typescript-plugin-add-type.jsx, /home/node_modules/typescript-plugin-add-type/index.js, /home/node_modules/typescript-plugin-add-type/index.jsx, /node_modules/typescript-plugin-add-type/package.json, /node_modules/typescript-plugin-add-type.js, /node_modules/typescript-plugin-add-type.jsx, /node_modules/typescript-plugin-add-type/index.js, /node_modules/typescript-plugin-add-type/index.jsx
    at Object.resolveJavaScriptModule (/home/sg/git/typescript-plugins-of-mine/common/temp/node_modules/typescript/lib/tsserver.js:6121:19)
    at Object.sys.require (/home/sg/git/typescript-plugins-of-mine/common/temp/node_modules/typescript/lib/tsserver.js:93621:45)
    at Function.Project.resolveModule (/home/sg/git/typescript-plugins-of-mine/common/temp/node_modules/typescript/lib/tsserver.js:87877:35)
    at ConfiguredProject.Project.enablePlugin (/home/sg/git/typescript-plugins-of-mine/common/temp/node_modules/typescript/lib/tsserver.js:88534:50)
    at ConfiguredProject.enablePlugins (/home/sg/git/typescript-plugins-of-mine/common/temp/node_modules/typescript/lib/tsserver.js:88693:30)
    at new ConfiguredProject (/home/sg/git/typescript-plugins-of-mine/common/temp/node_modules/typescript/lib/tsserver.js:88655:23)
    at ProjectService.createConfiguredProject (/home/sg/git/typescript-plugins-of-mine/common/temp/node_modules/typescript/lib/tsserver.js:89705:31)
    at ProjectService.openClientFileWithNormalizedPath (/home/sg/git/typescript-plugins-of-mine/common/temp/node_modules/typescript/lib/tsserver.js:90083:44)
    at IOSession.Session.openClientFile (/home/sg/git/typescript-plugins-of-mine/common/temp/node_modules/typescript/lib/tsserver.js:91488:37)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/home/sg/git/typescript-plugins-of-mine/common/temp/node_modules/typescript/lib/tsserver.js:90686:31)
    at /home/sg/git/typescript-plugins-of-mine/common/temp/node_modules/typescript/lib/tsserver.js:92160:88
    at IOSession.Session.executeWithRequestId (/home/sg/git/typescript-plugins-of-mine/common/temp/node_modules/typescript/lib/tsserver.js:92151:28)
    at IOSession.Session.executeCommand (/home/sg/git/typescript-plugins-of-mine/common/temp/node_modules/typescript/lib/tsserver.js:92160:33)
    at IOSession.Session.onMessage (/home/sg/git/typescript-plugins-of-mine/common/temp/node_modules/typescript/lib/tsserver.js:92180:35)
    at Interface.<anonymous> (/home/sg/git/typescript-plugins-of-mine/common/temp/node_modules/typescript/lib/tsserver.js:93377:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by nickpape-msft** [comment]
Hi @cancerberoSgx , rush definitely supports local linking. You will want to make sure that `example-project` has a dependency on `typescript-plugin-1` (and make sure the versions match -- rush won't link local projects if the version doesn't match). If you want to make sure that both of them can access `typescript`, just make sure to add the same version of typescript to both packages.

**Comment by nickpape-msft** [comment]
I'll try to get to the root of the issue in the next comment, but I have responses to some of your questions...

> I'm rebuilding everything with "all", this is, removing common/temp , all l node_modules and package-lock.json recursively k, and then executing " npm install && rush generate && rush install && rush link && npm run link-missing-modules && rush build "

You shouldn't be doing a "rush generate" as part of your standard build. Rush generate allows your shrinkwrap file to be changed, so if you are doing this in a normal build you are building against a non-deterministic set of dependencies. Also, you shouldn't need to be cleaning your common/temp/node_modules or package.lock files. `Rush install --clean` will ensure that those are cleaned for you. As for local node_modules, they are replaced whenever you run `rush link` (which is always run at the end of install and generate, so you don't need that step either).

> I'm executing first npm install because I want to use rush local version instead of global. Perhaps that's the cause of the problem?

You don't need to do this. If you specify the `rushVersion` field in `rush.json`, then Rush will always install that particular version and use it whenever you run commands in a repo.

**Comment by nickpape-msft** [comment]
> After the previous "all" commands rrush NEVER generates links my local projects in common/temp/node_modules so typescript files at runtime trying to load them from there. Again, (I guess) is a dynamic require() done my typescript at runtime that expects () to find its plugins in /common/temp/node_modules and they are not.

So it sounds like your problem is that you want links into the local projects that exist inside `common/temp/node_modules` ? And the reason for this is that typescript is expecting to find them all in one location? That's not a typical use case... Are the links to the plugins correct in `typescript-plugin-user-example`? Why is typescript not using that node_modules folder?

**Comment by cancerberoSgx** [comment]
> So it sounds like your problem is that you want links into the local projects that exist inside common/temp/node_modules ? And the reason for this is that typescript is expecting to find them all in one location? That's not a typical use case... Are the links to the plugins correct in typescript-plugin-user-example? Why is typescript not using that node_modules folder?

I don't know the internals of how TypeScript policy to resolve where to find plugins ( already shown where is searching). It seems it's using $REAL_TYPESCRIPT_FOLDER/../typescript-plugin-user-example or $USER_PACKAGE_REAL_FOLDER/node_modules/typescript-plugin 

Given the output for getting the plugin's path I think it has a complex plugin folder resolution algorithm (i's searching for it in a cascade of several folders).

But let's agree that this is not TypeScript issue - it's rush - the behavior should be the same as without it. 

typescript-plugin package.json:

```
"dependencies": {    
  "typescript": "^2.8.3"
```
typescript-plugin-example-project package.json:

```
  "devDependencies": {
    "typescript": "^2.8.3",
    "typescript-plugin-extract-interface": "1.0.0",
```

* Note that typescript is used as a local dependency in typescript-plugin-example-project. 
* Versions verified
* when you do all the setup for rush form scratch, like generate, install, link etc as documented in the 
* getting started. there is no link to the plugin in `common/temp/node_module` . That alone solves the issue and seems to be reasonable that local projects be linked there. And right now I need to do this manually.

**Comment by pgonzal** [comment]
@cancerberoSgx if you are still having this issue, could you provide a small repro that illustrates the problem?  From reading the comments here, it's still unclear to me whether this is a Rush problem or an external issue with how **typescript-plugin-extract-interface** is getting resolved.

**Comment by halfnibble** [comment]
Closing this due to inactivity. If this is still an issue, then please provide a repo with a minimal test case. Thanks!
